### ISSUE TITLE
StudioLink - Volume Anpassung

### ISSUE THREAD

**Issue by sreimers** [cogneon/lernos-podcasting#44]
https://github.com/cogneon/lernos-podcasting/blob/bfb06a343852f96de3f3209065c46ad4b7711332/de/src/2-5-8-Studio-Link.md#L16

Seit der [v21.07.0](https://sendegate.de/t/studiolink-v21-07-0-stable/14052) lässt sich die Lautstärke einstellen. Allerdings sollte das  nur benutzt werden wenn es keine andere Möglichkeit der lokalen Gain Anpassung gibt.

**Comment by simondueckert** [comment]
Danke für den Hinweis, werde ich ergänzen.
